# Site settings
name: V
email: kaiseryang@hotmail.com
author: Byrce Yang
url: http://www.kaiseryang.com
github: https://github.com/bryceyang/
baseurl:
description: Actually, less is more!
meta_description: learning
motto: It's our wits that make us men.
banner: Stay sharp.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: bryceyang
highlighter: Pygments

# Build settings
markdown: kramdown

#baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    disqus :
        short_name : bryceyang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
